# Generated by Django 4.0.4 on 2022-06-17 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Googlesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='№')),
                ('zakaz', models.IntegerField(verbose_name='Закакз №')),
                ('price_d', models.IntegerField(verbose_name='стоимость,$')),
                ('price_r', models.IntegerField(verbose_name='стоимость,руб.')),
                ('data', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='срок поставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
