# Generated by Django 4.0.4 on 2022-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheet',
            name='nomer',
            field=models.IntegerField(default=0, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='googlesheet',
            name='price_d',
            field=models.IntegerField(default=0, verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='googlesheet',
            name='price_r',
            field=models.IntegerField(default=0, verbose_name='стоимость,руб.'),
        ),
        migrations.AlterField(
            model_name='googlesheet',
            name='zakaz',
            field=models.IntegerField(default=0, verbose_name='Закакз №'),
        ),
    ]
